### ISSUE TITLE
Use text-transform CSS property to make text uppercase

### ISSUE THREAD

**Issue by guerrero** [puyhg5/puyhg5.github.io#1]
You are writting [all your `h` tags using uppercase text](https://github.com/puyhg5/puyhg5.github.io/blob/master/index.html#L57), this can be done but definitely it's not the way to go. Instead of use uppercase text you can [learn more about a CSS property called `text-transform`](https://developer.mozilla.org/es/docs/Web/CSS/text-transform). It lets you achieve the same result using CSS instead of relaying in the content.

Remember that style and format are managed by CSS and make text uppercase are related with format so it's better to use CSS instead to write uppercase text, you don't know if in the future you will change your mind.

So as a recommendation, and due that it's a good practice, I recommend you to use title case text in your headers and modify then using `text-transform`. Using this approach, if you change your mind in the future, you would only need to change one line instead of replace all the content inside your headers.

**Comment by puyhg5** [comment]
Thank you! [Done!](https://github.com/puyhg5/puyhg5.github.io/commit/4e91f650f107eb943d096c224f4ff0211ea29e01)
