### ISSUE TITLE
Use spaces instead of dashes for alt attributes

### ISSUE THREAD

**Issue by guerrero** [puyhg5/puyhg5.github.io#10]
You are currently using dashes in `alt` attributes (e.g. `alt="Mi-foto"`) but due that the values in this attributes should be read by people, machines and assistive devices for deaf people it is recommendable to use human readable text to make easier for these targets to understand what's the content of your images.

**Comment by puyhg5** [comment]
Ok, [done](https://github.com/puyhg5/puyhg5.github.io/commit/d293fe47e66a31b798e508ec0881f86bd5ce476d)! Thank you so much!
