### ISSUE TITLE
Replace local fonts by Google fonts

### ISSUE THREAD

**Issue by guerrero** [puyhg5/puyhg5.github.io#11]
You're using a local font (Montserrat) combined with remote fonts from Google. It's better to use only Google fonts or, in case you want to have everything in your repo, download the CSS from the Google font and its relative files. In your case, you are using `@font-face` but it only includes a OpenType font (`.otf`). OpenType fonts are supported in almost all browsers but there are [some exceptions](https://caniuse.com/#search=otf), Google knows how to deal with that and it includes some fallback for older browsers in order to use a supported format and makes the font works as expected.

If you [open the link that we use to embed the styles for the fonts](https://fonts.googleapis.com/css?family=Montserrat:400,700), you can see the CSS code that Google uses to import the fonts from Montserrat. To open it you can also grab the href value from the link and open it into your browser like the image below shows.

![captura de pantalla 2017-04-11 a las 13 30 23](https://cloud.githubusercontent.com/assets/3751801/24907110/0c23ec9e-1ebb-11e7-8116-94ad24cc346e.png)

**Comment by puyhg5** [comment]
Ok! [done](https://github.com/puyhg5/puyhg5.github.io/commit/9e7de009b0690c4bcbfde81c385cc01cba5338a7)
Thank you!
