### ISSUE TITLE
Remove padding:0 and margin:0 from the * selector

### ISSUE THREAD

**Issue by guerrero** [puyhg5/puyhg5.github.io#12]
Apply `padding: 0;` and `margin: 0;` to all your HTML elements is a bad practice because you can get unexpected results and you are modifying element that sometimes not need to be modified. Try to apply instead these styles to the specific elements you want to modify.

**Comment by puyhg5** [comment]
Thanks. [Done!](https://github.com/puyhg5/puyhg5.github.io/commit/b8fe76f64c33e1ca400a316f107275ec42adf7fd)
