### ISSUE TITLE
50% for border radius is enough

### ISSUE THREAD

**Issue by guerrero** [puyhg5/puyhg5.github.io#13]
You're using a percentage value in some of your border-radius attributes and that's perfect. The problem is that you've misunderstood how the border-radius works when a percentage is used as value. Once you know how it works you will learn that a `100%` is unnecesary for border-radius and therefore `50%` should be used instead.

Two resources to understand how `border-radius` works:
- [Border-radius: 50% vs 100%](http://jessica-eldredge.com/2014/09/07/border-radius-50-or-100-percent/)
- [StackOverflow response explaining how border-radius works when percentages are used](http://stackoverflow.com/a/29966500)

**Comment by puyhg5** [comment]
Thank you for resources! [done!](https://github.com/puyhg5/puyhg5.github.io/commit/9d969159d1f7f48942aff77f2658617ea8fa3066)
