### ISSUE TITLE
Replace empty div with margin in the social section

### ISSUE THREAD

**Issue by guerrero** [puyhg5/puyhg5.github.io#2]
[You are using an empty div as a margin for the `redes` element](https://github.com/puyhg5/puyhg5.github.io/blob/master/index.html#L30) but, instead, you can apply a real margin to the `redes` element and get rid of the div mentioned above. Try to use a margin with the same size as the `espacio` div.

**Comment by puyhg5** [comment]
[Done!](https://github.com/puyhg5/puyhg5.github.io/commit/bd5038d9a5b2ff5ca5edb4562db6196261137426)
