### ISSUE TITLE
Use English everywhere

### ISSUE THREAD

**Issue by guerrero** [puyhg5/puyhg5.github.io#3]
You have a mix between English and Spanish terms in your code (e.g. `container`, `espacio`, `grid`...) I recommend you to use only English terms for ids, classes and filenames. It's really easy to find how to say something in English using Google Translate, Linguee or WordReference and it will help you to learn English while you code. That means hitting two targets with one shot

![Time to Learn English](https://media.giphy.com/media/5ME9j9hbSJYrK/giphy.gif)

**Comment by puyhg5** [comment]
Yes, you are right!. From now on, all in english, I promise! (Love gif haha)
