### ISSUE TITLE
Replace <span class="nombre"> by <strong>

### ISSUE THREAD

**Issue by guerrero** [puyhg5/puyhg5.github.io#4]
[You're using `<span class="name">` to make some text semibold](https://github.com/puyhg5/puyhg5.github.io/blob/master/index.html#L82), it's better to use strong instead and modify the `strong` style using CSS.

**Comment by puyhg5** [comment]
[Done!](https://github.com/puyhg5/puyhg5.github.io/commit/895abce45dc99ea9dd9a17c25fe34bfe29b10202) Thank you!
