### ISSUE TITLE
Divs, divs everywhere :)

### ISSUE THREAD

**Issue by guerrero** [puyhg5/puyhg5.github.io#5]
![div-tags-div](https://cloud.githubusercontent.com/assets/3751801/24883724/7d582756-1e46-11e7-9a73-48c7088e9ec1.jpg)

As we've talked before, we should learn how to get rid of the unnecesary divs within our code. Remember that a div is only a tag displayed as a block element whose purpose is to group multiple elements. Any other case can be solved without using divs, some examples:
- ¿You have a `h1` tag within a flex element? No problem, in that case you can achieve the same result whether wrapping it into a div that modifying that `h1` to change its behaviour.
- ¿You need a border around your rounded image? No problem, you can apply all the styles directly to the image and delete the wrapper div
- ¿You need some padding around you `arriba` tag? No problem, add that padding directly to the `arriba` tag and get rid of its div wrapper.

These are some examples and cases I've found in your code but, as a rule of thumb, think that div will be only necessary to group items and wrap images inside flex items to prevent a flexbox bug.

**Comment by puyhg5** [comment]
Ok, I will try to internalize it and to use it correctly in the future :)
